project:
  type: website

website:
  title: "Data Science Corps Exemplar"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Introduction"
      - href: modules/data.qmd
        text: "Data"
      - href: modules/about.qmd
        text: "About"
      - href: modules/do_now.qmd
        text: "Do Now"
      - href: modules/github_help.qmd
        text: "Github Help"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true