project:
  type: website

website:
  title: "Data Science Corps Exemplar"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: "Introduction"
      - href: data.qmd
        text: "Data"
      - href: about.qmd
        text: "About"
      - href: do_now.qmd
        text: "Do Now"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true