project:
  type: website

website:
  title: "Data Science Corps Exemplar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: do_now.qmd
        text: Do Now

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



